### ISSUE TITLE
Error in Arithmetic Operators on Python Syntax page

### ISSUE THREAD

**Issue by ClimberMel** [sage-code/python#1]
Here is a change to syntax.html that would correct the error:
<tr>
<td>%</td>
<td>remainder</td>
<td>&nbsp;a=3%2 #result is 1</td>
</tr>

to replace:
<td>%</td>
<td>remainder</td>
<td>&nbsp;a=1/2 #result is 0.5</td>
</tr>

**Comment by elucian** [comment]
Good catch. Fixed and published.
